### PR TITLE
V3

### PR DESCRIPTION
**Pull request by lainsce**
This should make it even closer to the default elementary theme.

Here is a screenshot

Should fix issues #1 , #2 , #5 , #7 , #8 .

Recommended to move new tab button to the toolbar.

### CODE REVIEW

**Comment by lainsce** [comment]
I want to know what's the status on this Pull Request..

**Comment by mcovalt** [comment]
I haven't merged it because there are a few cosmetic errors on my desktop. However, I assume these are unique to my install if they look OK for you. I was planning to test in a VM.

On the other hand, I'm quite busy. Would you like to take ownership of this repo?

**Comment by lainsce** [comment]
I don't mind waiting for testing. :smile:

**Comment by lainsce** [comment]
I'll close this PR since @harveycabaguio already did a better job than me.

**Pull request closed without merging**
